### ISSUE TITLE
Add EUPL 1.1 licence statement to appropriate files

### ISSUE THREAD

**Issue by bencomp** [EHRI/ehri-rest#103]
As part of cleaning up code for release (#45), we need a licence statement. Because of the European and multilingual nature of the EHRI project, and our code sharing philosophy, we should use the European Union Public Licence v1.1. This is compatible with GPL v2, but available in 22 languages (users can choose) and matches with legal terms in all jurisdictions.

Licence introductions + texts: https://joinup.ec.europa.eu/software/page/eupl/licence-eupl

How to use: https://joinup.ec.europa.eu/software/page/eupl/eupl-guidelines

- [x] add to repo in the root
- [x] add to pom
- [x] add to all source files

**Comment by mikesname** [comment]
I did not know about this license. Looks like a good choice (i.e. quite liberal.) :+1: 

Still in favour of just sticking a single LICENSE file in the root of the repository and calling it a day.

**Comment by bencomp** [comment]
Hm, [the guidelines](https://joinup.ec.europa.eu/sites/default/files/ckeditor_files/files/EUPL%201_1%20Guidelines%20EN%20Joinup.pdf) say that a reference to the licence must be in every source file, as well as on the top level access page (i.e. in the repo root).

**Comment by bencomp** [comment]
I'm writing a Checkstyle check that checks that every Java file starts with

```
/*
 * Copyright 2015 EHRI partners
 *
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved by
 * the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing
 * permissions and limitations under the Licence.
 */
```

But who holds the copyright here? :)

**Comment by mikesname** [comment]
Via Reto, the portal has copyright EHRI Consortium 2015.

**Comment by mikesname** [comment]
While you're at it any chance to get checkstyle to work with JDK 1.6? It's getting annoying commenting it out of the pom every time I do a release.

**Comment by bencomp** [comment]
I might be naive, but can't you build using a JDK 7+ automatically building for Java 6? It appears that Java 7 is available through yum, so I will ask for an update.

**Comment by mikesname** [comment]
That would be better, I've given up even asking now, having had an open ICT issue for about 2 years.

**Comment by bencomp** [comment]
Mike P says:

> Copyright should be a list of full organisational names: for DANS, KCL, Göttingen - I don't think there was any others programming - unless there are code that can be identified as coming from a single institution (including fixes).
> However, it will be difficult to go through all of the code files, so I would suggest copyright for all partners, after all we are open sourcing it.

He suggests the following copyright holders:

> Data Archiving and Networked Services (an institute of Koninklijke Nederlandse Akademie van Wetenschappen), King's College London, Georg-August-Universitaet Goettingen Stiftung Oeffentlichen Rechts

The EHRI Consortium is not a legal entity, so it can't be the copyright holder.

**Comment by mikesname** [comment]
Sounds fine to me.

**Comment by mikepriddy** [comment]
EUPL v1.1 has been approved, with the copyright notice, by the PMB. Please make it so, in the easiest & most correct way - i.e. if possible in the header of all files.

Thanks.

**Comment by bencomp** [comment]
Pull request #139 completed the list by adding a licence reference in every source file.
