### ISSUE TITLE
Description ID namespace collides with hierarchies...

### ISSUE THREAD

**Issue by mikesname** [EHRI/ehri-rest#129]
While we're trying to fix ID problems.

Description IDs are created by appending the language code and optionally the description identifier code to the item ID. This means it will collide with child items of the described item that have identifiers resembling 3-letter ISO639-2 codes. :scream_cat: 

I propose using the  semi-colon as an alternate delimiter for description IDs, so for example, a description ID would like like `nl-r1-c1;eng-some_code`. 

I wouldn't suggest making these changes till after YV is imported, because they will involve some modifications to the EadImporter's handling of multiple descriptions.

**Comment by mikesname** [comment]
Mmmn, can't use semi-colons due to Jersey's support for matrix params (;foo=bar;bar=baz); a feature no-one uses. That just leaves the humble "period". 

@bencomp any thoughts before I go an commit some catastrophic blunder due to ignorance?

**Comment by bencomp** [comment]
Do you want to constrain yourself to using a single character separator? `--` or `-_-` or similar could work in theory, couldn't it?

Is it possible to test before going ahead with potential catastrophic blunders? ;)

**Comment by mikesname** [comment]
I thought about `--`, but it is a bit error prone since someone might think they can get the hierarchy by just splitting on `-`. They're also rather ugly. On the other hand, a `.` is not bad looking, and just about the last character I can think of that's URI-safe.

I do plan to test (and am!), but there are blunders and then there are blunders. It's the latter I'm worried about ;)

**Comment by mikesname** [comment]
Also, minor advantage of `.` over `;`: it's allowed in HTML4 DOM IDs.

**Comment by bencomp** [comment]
At the moment, I cannot think of other blunders you could make :)
