### ISSUE TITLE
Create a test to check annotations and links are untouched on description update

### ISSUE THREAD

**Issue by bencomp** [EHRI/ehri-rest#46]
I couldn't find existing tests for this.

Question: will links and annotations on -units- descriptions remain untouched when a new version of a description is imported?

Test:
1. import two EAD files
2. create a link between -units- descriptions from the EAD files
3. import changed versions of the EAD files
4. assert that the link still exists and works and that its content is unchanged

However, what should happen when the units in v1 of the EAD files are not in v2 of the files? Are descriptions removed too? Or did we ignore this case?

**Comment by mikesname** [comment]
This is addressed by ead sync and associated tests
