### ISSUE TITLE
Tweak slugification algo to remove leading and trailing hyphens...

### ISSUE THREAD

**Issue by mikesname** [EHRI/ehri-rest#83]
Currently the slugify function converts trailing non alphanumeric characters into hyphens. It also removes double-hyphens, but this wasn't instituted till there was already stuff in the DB with double hyphens in the slug.

Leading or trailing hyphens can lead to slugs with double hyphens that are then removed, which can then lead to confusing slug collisions (when slugifying items in a path with, say, a trailing comma - which is depressingly common.)

This would be a no-brainer but for the fact that changing the slugify algo now could then break updates for harvested items (though that case would be rare).

One solution would be to programmatically "fix" all the double-hyphen IDs (permalinks be damned, we haven't released publically yet) before changing it.

This would likewise entail being careful to check and potential integrity issues, since we use path IDs to do that.

**Comment by bencomp** [comment]
Slugification relates to #93.

**Comment by mikesname** [comment]
Going to close this because:

 - slugification was fixed in afef1f494b6f5898074b20660b56ced20e478843 because...
 - added some admin tools to re-generate re-slugified hierarchical IDs because...
 - the front-end now has a system in place to handle renamed items elegantly
