### ISSUE TITLE
Make documentary unit URLs shorter when unit ID includes parent's ID

### ISSUE THREAD

**Issue by bencomp** [EHRI/ehri-rest#93]
Some CHIs asked whether the URL for documentary units could be shorter and not include duplication when some documentary unit's `<unitid>` is `[parent ID][separator][child ID]`. The URL is based on the graph ID `__ID__`, which is the slugified version of the path.

This is related to #16. #16 has been resolved, but the suggested goal (`[country]-[repository]-[fonds]...-[item]`) creates too long URLs if intermediate levels' IDs include their parent IDs.

If we don't allow a child to have the exact same ID as its parent, then not including an ID part `"some ID"` when the next part starts with that value (e.g. `"some ID / item 1"`).

@mikesname does the front end rely on duplicate parts in URLs? Or can I submit my pull request that fixes this?

**Comment by bencomp** [comment]
I will add another small test that checks the ID generation of non-duplicate path parts before opening a pull request.

**Comment by mikesname** [comment]
@bencomp I might misunderstand you, but this is AFAIK an issue with the source data, hence my [PR](https://github.com/EHRI/ehri-ead-preprocessing/pulls) on the pre-processing repo.

An item **can** have the exact same ID as it's parent, and I imagine this is quite a common case. But the ID of a child should not be _prefixed_ by the ID of it's parent, i.e. it should be identified relative to it's parent, not absolute in the whole XML document (which is redundant).

You could imagine a hierarchy where all the identifiers where "1", which would result in a path of `country / repoid / 1 / 1 / 1 / 1 / 1`, and that would be perfectly valid. However, what I don't want is `country / repoid / t1 / t1-t2 / t1-t2-t3 / t1-t2-t3-t4` which produces the repetitive URLs.

Does that make sense?

**Comment by bencomp** [comment]
@mikesname you make perfect sense and I totally overlooked your work on this. However, it would affect the unit id as shown too. @lindareijnhoudt suggests to not do this in pre-processing.

I will ensure that if parent ID and child ID are exactly the same, they are not zapped.

**Comment by mikesname** [comment]
> However, it would affect the unit id as shown too.

Can you elaborate? We have to revitalize (or de-absolutize) the local identifier ("identifier") in order to calculate the graph global ID, no?

Feel free to expand the [documentation on identifiers](http://ehri.github.io/docs/api/ehri-rest/identifiers.html) ([source](https://github.com/EHRI/ehri-rest/blob/master/src/site/markdown/identifiers.md)) if there's something I've overlooked.

**Comment by bencomp** [comment]
If you change the unit ID in the source (e.g. `M.40.MAP` as a child of `M.40` would become `MAP` or even `.MAP`), it would show up short as in the source. Users may expect the full unit ID. Of course, if you create an additional ID instead of overwriting it, it's less of a problem.

Documentation on identifiers is #96.

**Comment by mikesname** [comment]
Yes, true, this is something that could potentially be done at import time, particularly since we maintain a sequence of parent ids. Just out of interest, what's the objection to doing it as a preprocess step (other than having to munge XML.)

**Comment by mikesname** [comment]
This was implemented/changed in the Great Url Rewrite.
