### ISSUE TITLE
Make importers truly generic

### ISSUE THREAD

**Issue by bencomp** [EHRI/ehri-rest#94]
As a follow-up to #14 and its fix #90, if there is time left, we could look at making the `AbstractImporter` really unaware of any possible intermediate data structures in use.

I think (some of) the things this would imply are:
- [ ] push all `extractX(T)` methods down, as they are helper methods to cope with intermediate data structures
- [ ] reference `MapImporter` where things need to be extracted and leave references to `AbstractImporter` only for `importItem()` calls.
- [ ] consider making `AbstractImporter` an `Interface`

Again, only when we have (free) time left.

**Comment by mikesname** [comment]
Various refactorings should have addressed most of this issue
