### ISSUE TITLE
Document importing EAC/EAG/EAD via REST

### ISSUE THREAD

**Issue by bencomp** [EHRI/ehri-rest#98]
Looking at [documentation about importing](https://github.com/EHRI/ehri-rest/blob/master/src/site/markdown/import.md), there are some todos:
- [ ] describe importing EAC
- [ ] describe importing EAG
- [ ] describe / link to documentation about importing via the REST interface

**Comment by mikesname** [comment]
Docs are here presently: http://ehri.github.io/docs/api/ehri-rest/ingest.html
